### ISSUE TITLE
computer has moveMarker

### ISSUE THREAD

**Issue by lmccz** [david8zhang/aram-mini#1]
https://github.com/david8zhang/aram-mini/blob/d0b220e20d3be876a3549a526890dff03f500696/src/core/champion/Champion.ts#L427

`
        if (this.isPlayerControlled) {
            if (!this.moveMarker) {
                this.moveMarker = this.game.add.circle(x, y, 5, 0x00ff00);
            } else {
                this.moveMarker.setPosition(x, y);
            };
        };
`

**Comment by lmccz** [comment]
Can 'movemark' be added and hidden after arrival

**Comment by lmccz** [comment]
Can hide 'moveMark' after arriving at the destination (my english is not well)

**Comment by david8zhang** [comment]
Thanks, I fixed in the latest commit.
